

// servicesdata.ts
export interface Service {
  title: string;
  slug: string;
  description: string;
  overview: string;
  keyFeatures: Array<{ name: string; icon: string }>;
  whatWeDo: string;
  mainimage: string;
  ourProcesses: string[];
  differencesFromCompetitors: string[];
  competitiveAdvantage: string[];
  examples: string[];
  benefits: string[];
  metrics: string[];
  roiMetrics: string[];
  clients: string[];
  targetSectors: string[];
  technologyStack: string[];
  innovations: string[];
  sustainabilityAspects: string[];
  valueProposition: string;
}




export const servicesData: Service[] = [
//   {
//     title: "System Integration & Turnkey Delivery",
//     slug: "system-integration-turnkey-delivery",
//     mainimage: "",
//     description: "We provide end-to-end system integration for surveillance, solar, and IoT solutions, covering design, multi-vendor integration, deployment, testing, commissioning, and lifecycle management.",
//     overview: "As a leading integrator, we deliver comprehensive turnkey solutions that combine security, renewable energy, and IT systems. Founded in 2006, with 18+ years of excellence, we focus on future-ready technology for secure and smart worlds.",
//     keyFeatures: [
//       { name: "End-to-End Integration", icon: "Link" },
//       { name: "Multi-Vendor Compatibility", icon: "Puzzle" },
//       { name: "Seamless Deployment", icon: "Rocket" },
//       { name: "Rigorous Testing", icon: "CheckCircle" },
//       { name: "Lifecycle Management", icon: "Repeat" },
//     ],
//     whatWeDo: "We handle full-spectrum integration for projects like nationwide surveillance and solar systems, aligning with goals such as public safety, environmental conservation, and urban optimization.",
//     ourProcesses: [
//       "Collaborate on custom solution design to blueprint systems.",
//       "Integrate products from multiple vendors for maximum compatibility.",
//       "Manage on-site or remote deployment, thorough testing, and commissioning.",
//       "Provide ongoing updates, maintenance, and upgrades for sustainability.",
//     ],
//     differencesFromCompetitors: [
//       "Full turnkey ownership with single-point accountability, reducing risks unlike fragmented services from others.",
//       "Proven scale with over 2M cameras installed, achieving faster deployments (e.g., 1,500 cameras in a week).",
//       "Focus on eco-friendly integrations, like non-disruptive installations in sensitive areas such as national parks.",
//     ],
//     competitiveAdvantage: [
//       "In-house manufacturing and R&D for customized, cost-effective solutions.",
//       "Nationwide presence with 12,000+ clients, enabling rapid scaling.",
//       "Integration of AI and IoT for intelligent, adaptive systems.",
//     ],
//     examples: [
//       "Installed 100,000+ cameras for 2023-2024 General Elections across India.",
//       "Commissioned 72 IP thermal and ANPR cameras at Kaziranga National Park without disturbing the environment.",
//       "Deployed 990kW solar project for Telangana State Road Transport Corporation.",
//       "Integrated surveillance with radio technology for sand mine projects.",
//     ],
//     benefits: [
//       "Reduced project risks and faster time-to-value through end-to-end ownership.",
//       "Seamless interoperability minimizing system silos and operational disruptions.",
//       "Cost-effective lifecycle management extending system longevity.",
//       "Eco-friendly solutions contributing to sustainability goals.",
//     ],
//     metrics: [
//       "Over 2 million cameras installed nationwide.",
//       "1,200+ projects completed.",
//       "Deployments in remote and critical locations within tight timelines.",
//       "300+ professionals ensuring execution excellence.",
//     ],
//     roiMetrics: [
//       "Up to 30% reduction in operational costs through efficient integrations.",
//       "Faster ROI with scalable systems handling peak loads.",
//       "Extended asset life via proactive maintenance, reducing replacement costs by 20-25%.",
//     ],
//     clients: [
//       "Election Commission of India (ECI)",
//       "Border Security Force (BSF)",
//       "Telangana State Road Transport Corporation (TGSRTC)",
//       "Kaziranga National Park",
//       "Indian Oil Corporation Limited (IOCL)",
//     ],
//     targetSectors: [
//       "Government",
//       "Defense",
//       "Transportation",
//       "Education",
//       "Energy",
//       "Wildlife Conservation",
//     ],
//     technologyStack: [
//       "IP Cameras",
//       "ANPR Systems",
//       "Thermal Imaging",
//       "Solar Panels",
//       "IoT Sensors",
//       "AI Analytics",
//     ],
//     innovations: [
//       "Non-disruptive eco-installations.",
//       "Radio-powered surveillance for remote areas.",
//       "Integrated solar-smart poles.",
//     ],
//     sustainabilityAspects: [
//       "Alignment with 'Make in India' for self-reliance.",
//       "Solar-powered solutions reducing carbon footprints.",
//       "Eco-friendly deployments in national parks.",
//     ],
//     valueProposition: "Delivering innovative, integrated solutions that ensure a connected, secure, and sustainable future with unmatched reliability and scale.",
//   },
  // Add remaining services from your original data...
  // (I've included the first one as an example - you can copy the rest from your original file)
   {
    title: "System Integration & Turnkey Delivery",
    slug: "system-integration-turnkey-delivery",
    mainimage:"/Service_images/Whisk_0754e12fd05e98396bd4695f1c03d21ddr.jpeg",
    description: "We provide end-to-end system integration for surveillance, solar, and IoT solutions, covering design, multi-vendor integration, deployment, testing, commissioning, and lifecycle management. Our turnkey approach ensures seamless interoperability across hardware, software, networks, and platforms.",
    overview: "As a leading integrator, we deliver comprehensive turnkey solutions that combine security, renewable energy, and IT systems. Founded in 2006, with 18+ years of excellence, we focus on future-ready technology for secure and smart worlds, aligning with 'Make in India' for self-reliance.",
    keyFeatures: [
      { name: "End-to-End Integration", icon: "Link" },
      { name: "Multi-Vendor Compatibility", icon: "Puzzle" },
      { name: "Seamless Deployment", icon: "Rocket" },
      { name: "Rigorous Testing", icon: "CheckCircle" },
      { name: "Lifecycle Management", icon: "Repeat" },
    ],
    whatWeDo: "We handle full-spectrum integration for projects like nationwide surveillance and solar systems, aligning with goals such as public safety, environmental conservation, and urban optimization.",
    ourProcesses: [
      "Collaborate on custom solution design to blueprint systems.",
      "Integrate products from multiple vendors for maximum compatibility.",
      "Manage on-site or remote deployment, thorough testing, and commissioning.",
      "Provide ongoing updates, maintenance, and upgrades for sustainability.",
    ],
    differencesFromCompetitors: [
      "Full turnkey ownership with single-point accountability, reducing risks unlike fragmented services from others.",
      "Proven scale with over 2M cameras installed, achieving faster deployments (e.g., 1,500 cameras in a week).",
      "Focus on eco-friendly integrations, like non-disruptive installations in sensitive areas such as national parks.",
    ],
    competitiveAdvantage: [
      "In-house manufacturing and R&D for customized, cost-effective solutions.",
      "Nationwide presence with 12,000+ clients, enabling rapid scaling.",
      "Integration of AI and IoT for intelligent, adaptive systems.",
    ],
    examples: [
      "Installed 100,000+ cameras for 2023-2024 General Elections across India.",
      "Commissioned 72 IP thermal and ANPR cameras at Kaziranga National Park without disturbing the environment.",
      "Deployed 990kW solar project for Telangana State Road Transport Corporation.",
      "Integrated surveillance with radio technology for sand mine projects.",
    ],
    benefits: [
      "Reduced project risks and faster time-to-value through end-to-end ownership.",
      "Seamless interoperability minimizing system silos and operational disruptions.",
      "Cost-effective lifecycle management extending system longevity.",
      "Eco-friendly solutions contributing to sustainability goals.",
    ],
    metrics: [
      "Over 2 million cameras installed nationwide.",
      "1,200+ projects completed.",
      "Deployments in remote and critical locations within tight timelines, e.g., 1,500 cameras in one week.",
      "300+ professionals ensuring execution excellence.",
    ],
    roiMetrics: [
      "Up to 30% reduction in operational costs through efficient integrations.",
      "Faster ROI with scalable systems handling peak loads, e.g., during elections.",
      "Extended asset life via proactive maintenance, reducing replacement costs by 20-25%.",
    ],
    clients: [
      "Election Commission of India (ECI)",
      "Border Security Force (BSF)",
      "Telangana State Road Transport Corporation (TGSRTC)",
      "Kaziranga National Park",
      "Indian Oil Corporation Limited (IOCL)",
    ],
    targetSectors: [
      "Government",
      "Defense",
      "Transportation",
      "Education",
      "Energy",
      "Wildlife Conservation",
    ],
    technologyStack: [
      "IP Cameras",
      "ANPR Systems",
      "Thermal Imaging",
      "Solar Panels",
      "IoT Sensors",
      "AI Analytics",
    ],
    innovations: [
      "Non-disruptive eco-installations.",
      "Radio-powered surveillance for remote areas.",
      "Integrated solar-smart poles.",
    ],
    sustainabilityAspects: [
      "Alignment with 'Make in India' for self-reliance.",
      "Solar-powered solutions reducing carbon footprints.",
      "Eco-friendly deployments in national parks.",
    ],
    valueProposition: "Delivering innovative, integrated solutions that ensure a connected, secure, and sustainable future with unmatched reliability and scale.",
  },
  {
    title: "Solution Engineering & Consulting",
    slug: "solution-engineering-consulting",
    mainimage:"/Service_images/Whisk_99cf8662196f446bd644bb8b8493d101dr (1).jpeg",
    description: "Our engineering team collaborates with government and institutions to translate requirements into scalable technical solutions, including analysis, architecture, project reports, and support for tenders.",
    overview: "With a dynamic team of 300+ professionals, we offer consulting in E-Security, IoT, IT, and renewable energy. Our expertise spans from requirement analysis to tender support, ensuring compliant, future-ready architectures for diverse sectors.",
    keyFeatures: [
      { name: "Requirement Analysis", icon: "Search" },
      { name: "Solution Architecture", icon: "Layout" },
      { name: "Project Report Preparation", icon: "FileText" },
      { name: "Tender Support", icon: "FileCheck" },
      { name: "Scalable Roadmaps", icon: "TrendingUp" },
    ],
    whatWeDo: "We serve as strategic partners for sectors like government, defense, and education, converting policies into deployable systems with expertise in surveillance and IT.",
    ourProcesses: [
      "Conduct stakeholder workshops and feasibility studies for requirements.",
      "Design architectures compliant with standards like UIDAI for biometrics.",
      "Prepare detailed project reports with costs, timelines, and ROI.",
      "Assist in RFP drafting, bid evaluation, and vendor selection.",
    ],
    differencesFromCompetitors: [
      "Domain expertise in public sector and defense, ensuring compliant solutions unlike general consultants.",
      "Objective, unbiased support with proven track record in large tenders.",
      "Emphasis on innovation, like AI integration, for sustainable and future-proof outcomes.",
    ],
    competitiveAdvantage: [
      "18+ years of tailored consulting experience.",
      "Integration of cutting-edge tech like 5G and AI.",
      "Proven in high-stakes tenders for solar and surveillance projects.",
    ],
    examples: [
      "Consulted for IP-based surveillance and ICCC for Maharashtra State Road Transport Corporation.",
      "Engineered Aadhaar-based biometric system for 932 PwDs schools in Maharashtra.",
      "Supported nationwide election monitoring setups for transparency and security.",
      "Advised on 5MW solar project for REIL Rajasthan.",
    ],
    benefits: [
      "Scalable, future-proof solutions aligned with policy requirements.",
      "Objective guidance reducing procurement risks and costs.",
      "Enhanced compliance with regulations like UIDAI and GDPR equivalents.",
      "Improved ROI through detailed project planning.",
    ],
    metrics: [
      "18+ years of experience in tech consulting.",
      "12,000+ satisfied clients across sectors.",
      "Successful tenders for projects like 5MW solar and nationwide surveillance.",
      "65,000+ cameras for NEET exams.",
    ],
    roiMetrics: [
      "Proven ROI with efficient tender processes saving 15-20% on procurement.",
      "Scalable designs handling growth, e.g., from 272 schools to nationwide.",
      "Long-term cost savings via sustainable architectures.",
    ],
    clients: [
      "Maharashtra Energy Development Agency (MEDA)",
      "Persons with Disabilities (PwDs) Welfare Department - Maharashtra",
      "National Testing Agency (NTA)",
      "Telangana State Board of Intermediate Education",
      "Rajasthan Electronics & Instruments Ltd (REIL)",
    ],
    targetSectors: [
      "Government",
      "Education",
      "Energy",
      "Defense",
      "Transportation",
    ],
    technologyStack: [
      "UIDAI Compliance",
      "AI Biometrics",
      "Solar Engineering Tools",
      "IoT Frameworks",
      "5G Integration",
    ],
    innovations: [
      "Aadhaar-integrated biometrics.",
      "AI-driven consulting for smart cities.",
      "Tender support for renewable projects.",
    ],
    sustainabilityAspects: [
      "Focus on green energy consulting.",
      "Eco-compliant designs for tenders.",
      "Promotion of sustainable tech adoption.",
    ],
    valueProposition: "Strategic engineering and consulting that translates visions into scalable, innovative solutions for a secure and sustainable tomorrow.",
  },
  {
    title: "Command & Control Centre Engineering",
    slug: "command-control-centre-engineering",
    mainimage:"/Service_images/Whisk_23c2e95d4db5a8085d24d8149e209d34dr.jpeg",
    description: "We design and implement Integrated Command & Control Centres (ICCC), including video walls, consoles, monitoring platforms, and backend infrastructure for real-time oversight.",
    overview: "Our ICCCs serve as central hubs for real-time monitoring in high-stakes environments. Leveraging VMS and analytics, we ensure 360° awareness for elections, exams, and security, with seamless integration of AI and IoT.",
    keyFeatures: [
      { name: "Video Walls & Displays", icon: "Monitor" },
      { name: "Operator Consoles", icon: "Armchair" },
      { name: "Centralized Platforms", icon: "Server" },
      { name: "Backend Infrastructure", icon: "Database" },
      { name: "AI Integration", icon: "Brain" },
    ],
    whatWeDo: "We build ICCCs as central hubs for monitoring in elections, exams, and security operations, enabling real-time decision-making in public safety and transportation.",
    ourProcesses: [
      "Design with high-resolution video walls and ergonomic consoles.",
      "Develop custom dashboards for data aggregation from CCTV and IoT.",
      "Integrate AI for analytics and predictive insights.",
      "Ensure high uptime with redundant systems and cybersecurity.",
    ],
    differencesFromCompetitors: [
      "Scalable designs handling millions of feeds, with real-time monitoring for nationwide events.",
      "Integrated with advanced features like ANPR and thermal imaging, unlike basic setups.",
      "Proven in high-stakes scenarios, reducing response times and operational costs.",
    ],
    competitiveAdvantage: [
      "In-house VMS for streamlined management.",
      "Real-time analytics for proactive responses.",
      "Nationwide deployments with zero disruptions.",
    ],
    examples: [
      "Set up ICCCs for General Elections 2024, monitoring 100,000+ cameras.",
      "Implemented centralized CCC for NEET 2025 exams across India.",
      "Engineered ICCC for Kolkata Metro's IP-based surveillance system.",
      "CCC for Telangana Intermediate Exams with 8,500+ cameras.",
    ],
    benefits: [
      "Enhanced situational awareness for quick decision-making.",
      "High uptime (99.99%) ensuring reliable operations.",
      "Cost savings through optimized resource allocation.",
      "Integrated AI for proactive threat detection.",
    ],
    metrics: [
      "Monitored 1.3 million students in MHCET exams over 45 days.",
      "Installed 8,500+ cameras for Telangana exams with real-time CCC.",
      "674 cameras for BSF borders with centralized control.",
      "4,500+ cameras for MHCET 2025.",
    ],
    roiMetrics: [
      "Reduced incident response times by 40%.",
      "Cost savings of 25% in monitoring operations.",
      "Improved transparency leading to higher stakeholder trust.",
    ],
    clients: [
      "Kolkata Metro Railway",
      "Maharashtra Common Entrance Test (MHCET)",
      "Election Commission of India (ECI)",
      "Dr. Narla Tatrao Thermal Power Station (NTTPS)",
      "High Court - AP & TG",
    ],
    targetSectors: [
      "Government",
      "Education",
      "Transportation",
      "Defense",
      "Law Enforcement",
    ],
    technologyStack: [
      "Video Walls",
      "SCADA Systems",
      "AI Analytics",
      "IoT Integration",
      "Cybersecure Backends",
    ],
    innovations: [
      "In-house VMS for election websites.",
      "AI-powered video analytics like ANPR and intrusion detection.",
      "Real-time streaming and playback.",
    ],
    sustainabilityAspects: [
      "Energy-efficient designs for long-term operations.",
      "Integration with solar-powered systems.",
    ],
    valueProposition: "Empowering real-time oversight with advanced ICCCs for enhanced security and operational efficiency.",
  },
  {
    title: "IT, Network & Digital Infrastructure",
    slug: "it-network-digital-infrastructure",
    mainimage:"/Service_images/Whisk_58d7195cc00c45d9e1e4b033aaa469a0dr.jpeg",
    description: "We deliver secure IT and telecom infrastructure, including data centers, servers, storage, networks, and cybersecurity architectures.",
    overview: "Serving as the backbone for modern operations, our IT and telecom solutions integrate high-speed internet, cloud, 5G, and automation. We provide comprehensive products like fiber optics, servers, and routers for seamless connectivity across India.",
    keyFeatures: [
      { name: "Data Centers & Servers", icon: "HardDrive" },
      { name: "Networking Solutions", icon: "Network" },
      { name: "Fiber Optic & Routers", icon: "Cable" },
      { name: "Cybersecurity", icon: "Shield" },
      { name: "Virtualization", icon: "Layers" },
    ],
    whatWeDo: "We provide end-to-end IT and telecom solutions, integrating 5G, cloud, and automation for efficient connectivity and data management.",
    ourProcesses: [
      "Design scalable infrastructures with Tier-level redundancy.",
      "Optimize servers and networks for high-speed, secure operations.",
      "Implement virtualization and automation for resource efficiency.",
      "Embed enterprise-grade cybersecurity with compliance standards.",
    ],
    differencesFromCompetitors: [
      "Future-ready with 5G and IoT integration, supporting global connectivity.",
      "Comprehensive product range including ANWI servers and Technorack enclosures.",
      "Proven in critical sectors, minimizing downtime and enhancing protection.",
    ],
    competitiveAdvantage: [
      "In-house manufacturing of servers and racks.",
      "Focus on speed, efficiency, and security.",
      "Nationwide innovation in telecom infrastructure.",
    ],
    examples: [
      "Supplied servers, switches, and routers for various IT infrastructures.",
      "Integrated networks for defense and government projects like BSF borders.",
      "Deployed digital infrastructure for CSIR-CCMB laboratories.",
      "Provided fiber optic solutions for high-speed connectivity.",
    ],
    benefits: [
      "Seamless global connectivity with high-speed networks.",
      "Enhanced data security and management.",
      "Efficiency gains through automation and virtualization.",
      "Future-ready infrastructure for emerging technologies like 5G.",
    ],
    metrics: [
      "300+ professionals handling IT projects.",
      "Integrated solutions for data centers and mobile networks.",
      "Support for cloud computing in 1,200+ projects.",
      "ANWI series laptops and AIOs deployed.",
    ],
    roiMetrics: [
      "Reduced infrastructure costs by 20% via optimized designs.",
      "Improved performance with 5G readiness.",
      "Faster deployment leading to quicker ROI.",
    ],
    clients: [
      "CSIR - CCMB, Hyderabad",
      "Atomic Minerals Directorate (AMD)",
      "Indian Oil Corporation Limited (IOCL)",
      "Tata Power Project",
      "DRDO",
    ],
    targetSectors: [
      "Government",
      "Defense",
      "Commercial",
      "Industrial",
      "Research Institutions",
    ],
    technologyStack: [
      "5G Networks",
      "Cloud Computing",
      "Fiber Optics",
      "ANWI Servers",
      "Technorack Enclosures",
      "Virtualization Tools",
    ],
    innovations: [
      "ANWI Zeno series laptops and AIOs.",
      "Advanced network interfaces.",
      "High-performance racks for data centers.",
    ],
    sustainabilityAspects: [
      "Energy-efficient servers and networks.",
      "Support for green data centers.",
    ],
    valueProposition: "Building robust IT and telecom backbones for efficient, secure, and future-ready operations.",
  },
  {
    title: "AI, Video Analytics & Platform Integration",
    slug: "ai-video-analytics-platform-integration",
    mainimage:"/Service_images/Whisk_02b3b2939fa1f239644437eb7c2baae5dr.jpeg",
    description: "We deploy AI-based analytics for video surveillance, transport, and safety, integrating with VMS, ICCCs, and legacy systems for actionable insights.",
    overview: "Leveraging AI-driven software, our analytics transform surveillance with features like object detection and facial recognition. Integrated with in-house VMS, we ensure real-time intelligence for security and operations.",
    keyFeatures: [
      { name: "AI Deployment", icon: "Bot" },
      { name: "Video Analytics", icon: "Video" },
      { name: "Platform Integration", icon: "Plug" },
      { name: "Dashboards & APIs", icon: "LayoutDashboard" },
      { name: "Object Detection", icon: "Search" },
    ],
    whatWeDo: "We transform video data into intelligence for applications in security, transport, and biometrics, using features like ANPR and facial recognition.",
    ourProcesses: [
      "Customize AI models for real-time detection and analysis.",
      "Integrate with VMS, ICCCs, dashboards, and APIs.",
      "Enable advanced features like intrusion and fall detection.",
      "Ensure ethical AI with anti-spoofing and privacy compliance.",
    ],
    differencesFromCompetitors: [
      "In-house VMS and analytics for seamless, cost-effective integrations.",
      "Advanced AI in products like TrinAI cameras, improving efficiency by up to 50%.",
      "Compliance-focused, with UIDAI integration for biometrics.",
    ],
    competitiveAdvantage: [
      "TrinAI manufacturing with AI GPUs.",
      "Real-time features like ANPR and face recognition.",
      "Ethical AI with anti-spoofing.",
    ],
    examples: [
      "Integrated AI analytics for Tata Power Project with 200+ cameras.",
      "Deployed video analytics in IOCL plants with flame-proof cameras.",
      "Implemented facial recognition biometrics for PwDs Welfare Department.",
      "AI in smart bus and in-car surveillance systems.",
    ],
    benefits: [
      "Actionable intelligence for proactive security measures.",
      "Improved efficiency in threat detection and response.",
      "Ethical AI ensuring privacy and bias mitigation.",
      "Seamless integration with existing systems avoiding replacements.",
    ],
    metrics: [
      "Real-time analytics for over 65,000+ cameras in exams.",
      "ANPR and thermal integration in 72 cameras for wildlife protection.",
      "Facial recognition deployed in 932 schools.",
      "Fall and intrusion detection in various sectors.",
    ],
    roiMetrics: [
      "50% improvement in detection efficiency.",
      "Reduced security incidents by 30-40%.",
      "Cost savings through automated monitoring.",
    ],
    clients: [
      "Persons with Disabilities (PwDs) Welfare Department",
      "Indian Oil Corporation Limited (IOCL)",
      "Tata Power Project",
      "Singareni Collieries Company Limited",
      "Border Security Force (BSF)",
    ],
    targetSectors: [
      "Government",
      "Defense",
      "Transportation",
      "Commercial",
      "Industrial",
      "Residential",
    ],
    technologyStack: [
      "TrinAI Cameras",
      "VMS Platforms",
      "ANPR Algorithms",
      "Facial Recognition",
      "Object Detection AI",
    ],
    innovations: [
      "Smart GPU with TrinAI for advanced surveillance.",
      "Aadhaar-authenticated biometrics.",
      "Video analytics for fall detection and space monitoring.",
    ],
    sustainabilityAspects: [
      "Energy-efficient AI processing.",
      "Integration with solar systems for green surveillance.",
    ],
    valueProposition: "Harnessing AI to deliver intelligent, actionable insights for enhanced security and efficiency.",
  },
  {
    title: "Program Management & Operations (O&M)",
    slug: "program-management-operations-om",
    mainimage:"/Service_images/Whisk_6aedc53dd4fa349b3474b15a466f460bdr.jpeg",
    description: "We execute large-scale projects with structured management, SLA-based operations, maintenance contracts, and managed services.",
    overview: "With 1,200+ completed projects, we manage end-to-end operations for government and institutional initiatives, ensuring SLA compliance, maintenance, and 24/7 monitoring for reliability.",
    keyFeatures: [
      { name: "Project Management", icon: "ClipboardList" },
      { name: "SLA Operations", icon: "Target" },
      { name: "Maintenance Contracts", icon: "Wrench" },
      { name: "Managed Services", icon: "DollarSign" },
      { name: "24/7 Monitoring", icon: "Eye" },
    ],
    whatWeDo: "We manage complex government and institutional projects, ensuring execution excellence and long-term reliability through SLAs and O&M.",
    ourProcesses: [
      "Follow structured methodologies for planning and stakeholder coordination.",
      "Guarantee performance with SLAs like high availability and quick responses.",
      "Provide annual maintenance for hardware and software updates.",
      "Offer OPEX-based services with 24/7 monitoring and support.",
    ],
    differencesFromCompetitors: [
      "Record-breaking deployments, like 65,000+ cameras for NEET exams.",
      "Long-term partnerships with cost reductions and regulatory compliance.",
      "Nationwide scale with over 1,200 completed projects.",
    ],
    competitiveAdvantage: [
      "300+ team for seamless execution.",
      "Proven in crises like pandemics with COVID devices.",
      "Integrated O&M with AI monitoring.",
    ],
    examples: [
      "Managed installation and O&M for 65,000+ cameras in NEET 2025.",
      "Executed border surveillance for BSF with 674 cameras.",
      "Handled O&M for Singareni Collieries with 2,000+ cameras.",
      "Managed 3,000 cameras for AP Agricultural Market Committee.",
    ],
    benefits: [
      "Reliable operations with minimized disruptions.",
      "Cost reductions through optimized maintenance.",
      "Regulatory adherence in high-stakes environments.",
      "Scalable management for national-level projects.",
    ],
    metrics: [
      "18+ years of project management excellence.",
      "300+ professionals ensuring SLA compliance.",
      "Zero major disruptions in institutional projects.",
      "12,000+ clients with 100% satisfaction in large deployments.",
    ],
    roiMetrics: [
      "25% operational cost reductions.",
      "Faster project completion, e.g., nationwide in weeks.",
      "High ROI through long-term maintenance contracts.",
    ],
    clients: [
      "National Testing Agency (NTA)",
      "Border Security Force (BSF)",
      "Singareni Collieries Company Limited",
      "High Court - AP & TG",
      "Agricultural Market Committee - AP",
    ],
    targetSectors: [
      "Government",
      "Education",
      "Mining",
      "Judiciary",
      "Agriculture",
    ],
    technologyStack: [
      "PMBOK/PRINCE2 Methodologies",
      "SLA Tools",
      "24/7 Monitoring Systems",
      "AI for Predictive Maintenance",
    ],
    innovations: [
      "O&M for AI-integrated systems.",
      "Rapid deployment models for elections.",
      "Managed services for renewable energy projects.",
    ],
    sustainabilityAspects: [
      "Eco-friendly maintenance practices.",
      "Support for green projects like solar.",
    ],
    valueProposition: "Ensuring flawless execution and sustained operations for mission-critical projects.",
  },
  {
    title: "Software Products & Services",
    slug: "software-products-services",
    mainimage:"/Service_images/Whisk_0a2f05f5fd66075a5fb423de8edd29fddr.jpeg",
    description: "We offer AI-driven software development, including web design, app development, IoT applications, E-Communication, and Biz Track ERP for enterprises.",
    overview: "From foundational web development in 2006 to advanced AI software, we provide comprehensive software solutions like E-Communication platforms and automation-centric ERP, enhancing business efficiency across domains.",
    keyFeatures: [
      { name: "Web & App Development", icon: "Code" },
      { name: "Domain & Hosting", icon: "Globe" },
      { name: "IoT Applications", icon: "Cpu" },
      { name: "E-Communication", icon: "MessageSquare" },
      { name: "ERP Systems", icon: "Database" },
    ],
    whatWeDo: "We develop and deploy software for communication, automation, and management, tailored for small to enterprise businesses.",
    ourProcesses: [
      "Analyze business needs for custom development.",
      "Design user-centric interfaces and architectures.",
      "Implement with agile methodologies.",
      "Test and deploy with ongoing support.",
    ],
    differencesFromCompetitors: [
      "Automation-centric ERP unlike rigid systems.",
      "Integrated E-Communication with AI chatbots.",
      "Proven in diverse sectors with seamless integrations.",
    ],
    competitiveAdvantage: [
      "First-ever automation-centric ERP.",
      "Multi-channel communication tools.",
      "AI-driven insights for business optimization.",
    ],
    examples: [
      "Developed vehicle tracking software for AP Beverages Corporation.",
      "Implemented Biz Track ERP for CRM, sales, and HR.",
      "E-Communication for bulk SMS and IVR in marketing.",
    ],
    benefits: [
      "Streamlined operations with automation.",
      "Enhanced customer engagement via personalized communication.",
      "Real-time insights for decision-making.",
      "Scalable software for business growth.",
    ],
    metrics: [
      "Used in 12,000+ client operations.",
      "Supports 24/7 E-commerce-like sales.",
      "HR management for motivated workforces.",
    ],
    roiMetrics: [
      "Increased sales through efficient order handling.",
      "Reduced response times in services.",
      "Optimized inventory flow for cost savings.",
    ],
    clients: [
      "AP Beverages Corporation Limited",
      "Various SMEs and Enterprises",
    ],
    targetSectors: [
      "Commercial",
      "Manufacturing",
      "Services",
      "Government",
    ],
    technologyStack: [
      "AI Chatbots",
      "RCS/IVR",
      "CRM Modules",
      "Analytics Tools",
      "Cloud Hosting",
    ],
    innovations: [
      "Biz Track - First automation-centric ERP.",
      "Intelligent E-Communication platform.",
      "IoT app services for global challenges.",
    ],
    sustainabilityAspects: [
      "Digital solutions reducing paper usage.",
      "Efficient resource management in ERP.",
    ],
    valueProposition: "Transforming businesses with AI-driven software for efficiency and growth.",
  },
  {
    title: "Renewable Energy Solutions",
    slug: "renewable-energy-solutions",
    mainimage:"/Service_images/Whisk_0ec60332bbdcdd09c3e46cc3f284ea16dr (1).jpeg",
    description: "We provide solar rooftop systems, smart poles, and integrated renewable solutions for residential and commercial applications.",
    overview: "Committed to a greener future, we integrate solar technology with surveillance and IoT, supporting 'Make in India' with high-quality, efficient systems that minimize carbon footprints.",
    keyFeatures: [
      { name: "Solar Rooftop", icon: "Sun" },
      { name: "Solar Smart Pole", icon: "Zap" },
      { name: "Energy Integration", icon: "Battery" },
      { name: "CCTV & WiFi", icon: "Wifi" },
      { name: "Sustainable Design", icon: "Leaf" },
    ],
    whatWeDo: "We design and install renewable energy systems, combining solar with security for standalone, eco-friendly solutions.",
    ourProcesses: [
      "Assess site for optimal solar design.",
      "Integrate with surveillance and connectivity.",
      "Install with minimal disruption.",
      "Provide maintenance for long-term performance.",
    ],
    differencesFromCompetitors: [
      "Integrated smart poles with surveillance, unlike standalone solar.",
      "Proven in large projects like 5MW and 990kW.",
      "Focus on sustainability and self-reliance.",
    ],
    competitiveAdvantage: [
      "Standalone solar-powered poles.",
      "Combination of energy and security.",
      "Awards from REIL, MEDA, TGSRTC.",
    ],
    examples: [
      "5MW solar project for REIL Rajasthan.",
      "272 Zilla Parishad schools solar for MEDA Maharashtra.",
      "990kW solar for TGSRTC Telangana.",
    ],
    benefits: [
      "Affordable clean energy access.",
      "Reduced carbon footprints.",
      "Enhanced urban safety with smart poles.",
      "Reliable performance in off-grid areas.",
    ],
    metrics: [
      "Multiple MW-scale projects completed.",
      "Solar smart poles deployed for urban security.",
      "Eco-friendly installations across states.",
    ],
    roiMetrics: [
      "Quick payback through energy savings.",
      "Long-term cost reductions in electricity.",
      "Added value from integrated security.",
    ],
    clients: [
      "Rajasthan Electronics & Instruments Ltd (REIL)",
      "Maharashtra Energy Development Agency (MEDA)",
      "Telangana State Road Transport Corporation (TGSRTC)",
    ],
    targetSectors: [
      "Education",
      "Transportation",
      "Government",
      "Urban Development",
    ],
    technologyStack: [
      "Solar Panels",
      "CCTV Integration",
      "WiFi Hotspots",
      "PA Systems",
      "Charging Points",
    ],
    innovations: [
      "Solar Smart Pole with comprehensive features.",
      "COVID-19 devices exemplifying commitment.",
      "Futuristic IP thermal in conservation.",
    ],
    sustainabilityAspects: [
      "Promoting renewable energy.",
      "Eco-friendly, standalone solutions.",
      "Contribution to greener future.",
    ],
    valueProposition: "Powering sustainable futures with integrated renewable solutions.",
  },
  {
    title: "Smart Bus Solutions",
    slug: "smart-bus-solutions",
    mainimage:"/Service_images/Whisk_ce854c95264034882294dfbfc253026cdr (1).jpeg",
    description: "We offer technology-integrated bus systems for efficiency, safety, and reliability in public and private transit.",
    overview: "Modernizing transportation with AI CCTV, GPS, and analytics, our smart bus solutions enhance passenger experience and operator oversight.",
    keyFeatures: [
      { name: "AI CCTV", icon: "Video" },
      { name: "GPS Tracking", icon: "MapPin" },
      { name: "WiFi Hotspot", icon: "Wifi" },
      { name: "Breath Analyzer", icon: "Activity" },
      { name: "Big Data Analytics", icon: "BarChart" },
    ],
    whatWeDo: "We integrate smart technologies for buses, including surveillance, announcements, and analytics for better transit management.",
    ourProcesses: [
      "Design system for specific transit needs.",
      "Install hardware like cameras and screens.",
      "Integrate software for real-time data.",
      "Monitor and maintain for ongoing reliability.",
    ],
    differencesFromCompetitors: [
      "Comprehensive features like foam fire suppression.",
      "AI for fatigue and blind spot detection.",
      "Future-ready with smart ticketing.",
    ],
    competitiveAdvantage: [
      "All-in-one integration for safety and revenue.",
      "Proven in large-scale transit projects.",
      "Data-driven optimizations.",
    ],
    examples: [
      "Deployed for public transport corporations.",
      "Integrated in buses for real-time monitoring.",
    ],
    benefits: [
      "Enhanced passenger safety and convenience.",
      "Efficient route management.",
      "Revenue generation via ads.",
      "Sober driving assurance.",
    ],
    metrics: [
      "Multiple camera views per bus.",
      "Real-time analytics for patterns.",
      "Improved service reliability.",
    ],
    roiMetrics: [
      "Reduced accidents through AI monitoring.",
      "Increased revenue from targeted ads.",
      "Operational efficiency gains.",
    ],
    clients: [
      "State Road Transport Corporations",
    ],
    targetSectors: [
      "Transportation",
      "Public Transit",
    ],
    technologyStack: [
      "MDVR",
      "DMS Cameras",
      "LED Displays",
      "Passenger Counters",
      "Foam Fire Systems",
    ],
    innovations: [
      "Blind spot pedestrian detection.",
      "Fatigue driving state detection.",
      "Smart ticketing in future.",
    ],
    sustainabilityAspects: [
      "Efficient fuel use via route optimization.",
      "Eco-friendly transit enhancements.",
    ],
    valueProposition: "Revolutionizing bus travel with smart, safe, and efficient solutions.",
  },
  {
    title: "Law Enforcement - In-Car Surveillance",
    slug: "law-enforcement-in-car-surveillance",
    mainimage:"/Service_images/Whisk_c4eb0a7bde8108db0434b643fced3b56dr (1).jpeg",
    description: "We provide AI-powered in-car systems for police with video monitoring, recognition, and analytics.",
    overview: "Designed for modern policing, our in-car surveillance enhances operations with 360° awareness, evidence collection, and incident response.",
    keyFeatures: [
      { name: "Facial Recognition", icon: "User" },
      { name: "License Plate Reading", icon: "Hash" },
      { name: "Driver Monitoring", icon: "AlertCircle" },
      { name: "Weapon Detection", icon: "ShieldAlert" },
      { name: "GPS Tracking", icon: "MapPin" },
    ],
    whatWeDo: "We equip police vehicles with integrated surveillance for patrolling, elections, and border security.",
    ourProcesses: [
      "Install cameras and AI-MDVR in vehicles.",
      "Integrate control panels and software.",
      "Train on usage and maintenance.",
      "Provide ongoing support.",
    ],
    differencesFromCompetitors: [
      "360° situational awareness.",
      "Integrated PTZ and smart light-bars.",
      "Applications in diverse law enforcement scenarios.",
    ],
    competitiveAdvantage: [
      "AI for real-time intelligence.",
      "Evidence playback and export.",
      "Connected vehicle ecosystem.",
    ],
    examples: [
      "Used in election duty surveillance.",
      "Deployed for prisoner transport vans.",
      "Implemented in border security vehicles.",
    ],
    benefits: [
      "Safer patrolling and evidence collection.",
      "Faster incident response.",
      "Enhanced monitoring for high-risk duties.",
    ],
    metrics: [
      "Multiple cameras per vehicle.",
      "Real-time analytics.",
      "Proven in national security projects.",
    ],
    roiMetrics: [
      "Reduced response times.",
      "Improved evidence quality.",
      "Cost savings in operations.",
    ],
    clients: [
      "Law Enforcement Agencies",
      "Border Security Force",
      "Election Authorities",
    ],
    targetSectors: [
      "Law Enforcement",
      "Defense",
      "Government",
    ],
    technologyStack: [
      "AI-MDVR",
      "PTZ Cameras",
      "Body Worn Cameras",
      "ALPR",
      "Software Platforms",
    ],
    innovations: [
      "Weapon detection AI.",
      "Driver behavior monitoring.",
      "Integrated with VMS.",
    ],
    sustainabilityAspects: [
      "Efficient power usage in vehicles.",
    ],
    valueProposition: "Empowering law enforcement with intelligent in-car surveillance for modern challenges.",
  },
  {
    title: "AI Biometric with Aadhaar Authentication",
    slug: "ai-biometric-aadhaar-authentication",
    mainimage:"/Service_images/Whisk_7201afdec8bd7b4a6aa4c45f3d5a4c01dr (1).jpeg",
    description: "We offer next-gen AI biometrics integrated with Aadhaar for contactless identity verification.",
    overview: "Designed for institutions, our biometric solutions ensure fraud-proof attendance and compliance with UIDAI standards, enhancing transparency.",
    keyFeatures: [
      { name: "Aadhaar Authentication", icon: "Key" },
      { name: "Facial Recognition", icon: "UserCheck" },
      { name: "Smart Dashboard", icon: "LayoutDashboard" },
      { name: "Alerts & Notifications", icon: "Bell" },
      { name: "Cloud Storage", icon: "Cloud" },
    ],
    whatWeDo: "We deploy biometrics for attendance in schools, hostels, and government departments, eliminating proxies.",
    ourProcesses: [
      "Integrate with UIDAI for OTP verification.",
      "Implement AI for live detection.",
      "Set up dashboards and alerts.",
      "Ensure secure cloud storage.",
    ],
    differencesFromCompetitors: [
      "Contactless, anti-spoofing technology.",
      "Battery backup and GPS for theft-proofing.",
      "Multi-face detection.",
    ],
    competitiveAdvantage: [
      "Full UIDAI compliance.",
      "Real-time insights and reporting.",
      "Touch screen interfaces.",
    ],
    examples: [
      "Implemented in 932 PwDs schools and workshops.",
      "Used in educational institutions for attendance.",
    ],
    benefits: [
      "Fraud-proof identity verification.",
      "Instant updates to parents.",
      "Uninterrupted operations with backups.",
      "Enhanced operational transparency.",
    ],
    metrics: [
      "Deployed across 932 locations.",
      "Real-time logs for millions of users.",
    ],
    roiMetrics: [
      "Reduced proxy attendance issues.",
      "Cost savings in manual tracking.",
    ],
    clients: [
      "PwDs Welfare Department - Maharashtra",
      "Educational Institutions",
      "Government Departments",
    ],
    targetSectors: [
      "Education",
      "Government",
      "Welfare",
    ],
    technologyStack: [
      "UIDAI API",
      "AI Facial Models",
      "GPS Tracking",
      "Cloud Encryption",
    ],
    innovations: [
      "Live presence with mask detection.",
      "OTP-based Aadhaar verification.",
      "Theft-proof hardware.",
    ],
    sustainabilityAspects: [
      "Digital reduction in paper records.",
    ],
    valueProposition: "Secure, intelligent biometrics for transparent and efficient identity management.",
  },
];